### ISSUE TITLE
cannot build: Value of onConflict must be one of ...

### ISSUE THREAD

**Issue by n-keist** [Amir-P/flat#19]
Hi, 

I'm getting this error whenever I try to run the generator. 
This also happens only on insert methods.. 

Error: 
```log
[SEVERE] flat_generator:flat_generator on lib/database/database.dart (cached):

Value of onConflict must be one of OnConflictStrategy.replace,OnConflictStrategy.rollback,OnConflictStrategy.abort,OnConflictStrategy.fail,OnConflictStrategy.ignore
package:napp_flutter/database/dao/base_dao.dart:6:16
  ╷
6 │   Future<void> insert(T item);
  │                ^^^^^^
  ╵
[SEVERE] Failed after 93ms
```

this is my code: 
```dart
@Insert(onConflict: OnConflictStrategy.replace)
Future<void> insert(T item);
```

I was already getting this issue with original floor, any ideas why this is happening?

**Comment by Amir-P** [comment]
Hi @n-keist ,
I have already fixed this issue in a local branch but it needs a bit testing. I will try to test and publish it the next week. Will let you know.

**Comment by Amir-P** [comment]
Can you please test and give me feedback on #20 ? @n-keist

**Comment by szeidner** [comment]
Hi @Amir-P there is a similar issue with foreign keys (I get the error below). Would it be possible to create a fix for these as well? Thanks!

```
No ForeignKeyAction with the value ForeignKeyAction (_name = String ('noAction'); index = int (0)) exists for the onUpdate trigger.
```

**Comment by szeidner** [comment]
@Amir-P This branch fixed the issue for me! Also, it fixed a similar issue with foreign keys not recognizing the enum values.

**Comment by Amir-P** [comment]
> @Amir-P This branch fixed the issue for me! Also, it fixed a similar issue with foreign keys not recognizing the enum values.

Great! I'm gonna merge #20 and release on pub.dev. @szeidner
